python/lsst/analysis/tools/contexts/__init__.py, python/lsst/analysis/tools/contexts/_baseContext.py, python/lsst/analysis/tools/contexts/_contexts.py, python/lsst/analysis/tools/interfaces.py, tests/test_contexts.py
Add a feature which will allow specifying a context for
AnalysisTools to run within. Each AnalysisAction can specify a
behavior for if a context is entered. If no behavior is defined on
an AnalysisAction then nothing happens.
=> DM-35614: Add Contexts

python/lsst/analysis/tools/actions/vector/selectors.py, python/lsst/analysis/tools/analysisMetrics/__init__.py, python/lsst/analysis/tools/analysisMetrics/analysisMetrics.py, python/lsst/analysis/tools/analysisMetrics/limitingMagnitudeMetric.py, python/lsst/analysis/tools/analysisMetrics/skyFluxStatisticMetrics.py, python/lsst/analysis/tools/interfaces.py, python/lsst/analysis/tools/tasks/objectTableTractAnalysis.py, python/lsst/analysis/tools/tasks/sourceTableVisitAnalysis.py
In addition to the 5-sigma limiting magnitude calculation, I also added sky source statistics. For the sky stats, I moved them into their own standalone file containing both the objectTable and sourceTable versions.
=> DM-35624: Create a task in analysis_tools to measure per-visit metrics

pipelines/apCcdVisitQualityCore.yaml, python/lsst/analysis/tools/actions/plot/diaSkyPlot.py, python/lsst/analysis/tools/actions/plot/plotUtils.py, python/lsst/analysis/tools/analysisPlots/__init__.py, python/lsst/analysis/tools/analysisPlots/simpleDiaPlot.py
This PR adds a new plotting capability for DiaSources on the sky. The simple version of this plot is here in `analysis_tools`, and a specialized version for a specific AP QA data set is in `analysis_ap`.
=> DM-29421: Add AP plots in analysis_ap using analysis_tools

python/lsst/analysis/tools/actions/plot/colorColorFitPlot.py, python/lsst/analysis/tools/actions/plot/plotUtils.py, python/lsst/analysis/tools/actions/plot/scatterplotWithTwoHists.py, python/lsst/analysis/tools/actions/plot/skyPlot.py, python/lsst/analysis/tools/analysisPlots/magDiff.py
Convert `plot_CModel_sub_PSFmag_meas_sky_galaxies` to analysis tools
This also required:
Change np.median -> np.nanmedian
Change np.mean -> np.nanmean
nan_policy="omit"
=> DM-35632: Port CModel PSFmag gal sky plot to analysis tools

pipelines/coaddColumnValidate.yaml, pipelines/visitColumnValidate.yaml, python/lsst/analysis/tools/actions/scalar/scalarActions.py, python/lsst/analysis/tools/analysisMetrics/analysisMetrics.py
As implemented on this ticket, the `ValidFracColumnMetric` will check what percentage (or fraction) of a column's values are NaNs, and what percentage lie within a specified range of values (for example, a "reasonable" range of flux for object measurements). These are meant for catalog validation purposes. At present, the only metrics implemented are checks on fluxes in SourceTable and ObjectTable. The "valid range" could be applied to any quantity of interest.
I also fixed a docstring in the `CountAction`, and removed an unnecessary (and possibly breaking) **kwargs in the `FracThreshold` action.
=> DM-37052: Implement metrics that calculate whether table columns are "well formed"

python/lsst/analysis/tools/actions/plot/plotUtils.py, python/lsst/analysis/tools/tasks/objectTableSurveyAnalysis.py, tests/test_plotUtils.py
This PR adds a utility function to `plotUtils` and unit tests for it. It also copies the unit tests for other `plotUtils` functions from `analysis_drp`.
=> DM-37330: Add a utility function to compress tract list

pipelines/matchedVisitQualityCore.yaml, python/lsst/analysis/tools/actions/plot/histPlot.py, python/lsst/analysis/tools/analysisParts/photometricRepeatability.py, python/lsst/analysis/tools/analysisPlots/__init__.py, python/lsst/analysis/tools/analysisPlots/photometricRepeatabilityPlots.py
The main change in this ticket is adding the ability to specify the stats to be shown on hist plot. They can be any scalar that has a vector key in the data (calculated in the body of the metric/plot). If no stats are specified this behaves as before where the N, median, and sigma mad are shown.
=> DM-36444: photRepeatHistPlot and Configurable stats panel

.git-blame-ignore-revs, python/lsst/analysis/tools/actions/plot/barPlots.py, python/lsst/analysis/tools/actions/plot/colorColorFitPlot.py, python/lsst/analysis/tools/actions/plot/plotUtils.py, python/lsst/analysis/tools/actions/plot/scatterplotWithTwoHists.py, python/lsst/analysis/tools/actions/plot/skyPlot.py, python/lsst/analysis/tools/analysisPlots/diffMatchedPlots.py, python/lsst/analysis/tools/tasks/catalogMatch.py, python/lsst/analysis/tools/tasks/diaObjectTableAssocAnalysis.py, python/lsst/analysis/tools/tasks/diaSourceTableVisitAnalysis.py, python/lsst/analysis/tools/tasks/objectTableSurveyAnalysis.py, python/lsst/analysis/tools/tasks/sourceTableVisitAnalysis.py
This was previously done in `analysis drp` ([DM-35371](https://github.com/lsst/analysis_drp/pull/49)) and this pull request moves it to `analysis tools`.
=> DM-37452: Port reference line in scatter plot to analysis tools

python/lsst/analysis/tools/actions/plot/histPlot.py
fix behavior where default stats are not shown
=> DM-38004: Fix metrics printing in histPlot

python/lsst/analysis/tools/__init__.py, python/lsst/analysis/tools/actions/keyedData/keyedDataActions.py, python/lsst/analysis/tools/actions/plot/scatterplotWithTwoHists.py, python/lsst/analysis/tools/actions/vector/calcBinnedStats.py, python/lsst/analysis/tools/actions/vector/ellipticity.py, python/lsst/analysis/tools/actions/vector/vectorActions.py, python/lsst/analysis/tools/analysisParts/base.py, python/lsst/analysis/tools/analysisParts/shapeSizeFractional.py, python/lsst/analysis/tools/contexts/_baseContext.py, python/lsst/analysis/tools/interfaces.py, python/lsst/analysis/tools/tasks/base.py, python/lsst/analysis/tools/tasks/catalogMatch.py, tests/test_contexts.py, ups/analysis_tools.table
Configurable Actions have moved to pex_config, update all the imports to reflect the new location.
=> DM-36649 Update import paths to pex_config

tests/test_catalogMatch.py
Rather than using a version defined locally.
Requires lsst/meas_algorithms#316.
=> DM-38753: Use the MockRefcatDataId from meas_algorithms

python/lsst/analysis/tools/interfaces/datastore/_dispatcher.py, python/lsst/analysis/tools/interfaces/datastore/_sasquatchDatastore.py
Handle failure modes in Sasquatch Dispatching where the reference_package is a None value, and when there is no data in a bundle to upload.
=> DM-39089: Handle failure modes in Sasquatch Dispatch

doc/lsst.analysis.tools/getting-started.rst
This was part of the 2023 SIT-COM bootcamp.
=> DM-39362: Change a line in analysis tools for bootcamp

.gitignore, bin.src/SConscript, bin.src/verify_to_sasquatch.py, doc/lsst.analysis.tools/action-types.rst, doc/lsst.analysis.tools/index.rst, doc/lsst.analysis.tools/scripts/verify_to_sasquatch.py.rst, python/lsst/analysis/tools/bin/verifyToSasquatch.py, python/lsst/analysis/tools/interfaces/datastore/_dispatcher.py, setup.cfg, tests/test_verifyToSasquatch.py, ups/analysis_tools.table
This PR adds a new script, `verify_to_sasquatch.py`, that provides backwards-compatibility support for `lsst.verify` metrics persisted directly to a Butler repository. The script implements functionality similar to `dispatch_verify.py`, but backed by `SasquatchDispatcher`.
=> DM-39143: Implement script for uploading free metrics to Sasquatch

python/lsst/analysis/tools/actions/vector/vectorActions.py
The numpy.warnings alias has been removed.
=> DM-39726: Use warnings instead of numpy.warnings

python/lsst/analysis/tools/actions/plot/histPlot.py
Set's iteration order is nondeterministic across different processes, while ListField remembers that order, so this makes configurations generated in different processes spuriously unequal.
=> DM-39672: Don't use a `set` as the default for a config ListField.

pipelines/coaddDiffMatchedQualityExtended.yaml, pipelines/coaddQualityExtended.yaml, python/lsst/analysis/tools/actions/plot/scatterplotWithTwoHists.py, python/lsst/analysis/tools/actions/vector/__init__.py, python/lsst/analysis/tools/actions/vector/calcBinnedStats.py, python/lsst/analysis/tools/actions/vector/calcMomentSize.py, python/lsst/analysis/tools/actions/vector/calcRhoStatistics.py, python/lsst/analysis/tools/actions/vector/mathActions.py, python/lsst/analysis/tools/atools/__init__.py, python/lsst/analysis/tools/atools/diffMatched.py, python/lsst/analysis/tools/atools/genericBuild.py, python/lsst/analysis/tools/atools/genericProduce.py, python/lsst/analysis/tools/atools/shapes.py, python/lsst/analysis/tools/atools/sizeMagnitude.py, python/lsst/analysis/tools/contexts/_contexts.py, tests/test_actions.py, tests/test_metrics.py, tests/test_psfResiduals.py
This also includes a significant refactoring of matched difference plots/metrics so that they share some base classes.
=> DM-36446: Add size vs magnitude plots to analysis_tools

python/lsst/analysis/tools/interfaces/_task.py
There is no reason to use the semi-private internal path.
=> DM-39661: Import ButlerQuantumContext directly from lsst.pipe.base

python/lsst/analysis/tools/bin/verifyToSasquatch.py, tests/test_verifyToSasquatch.py
This PR implements an `--extras` command-line argument for `verify_to_sasquatch.py`, allowing a dict for `SasquatchDispatcher.dispatch` to be specified on the command line. This will be used by the `scipipe/ap_verify` and `sqre/verify_drp_metrics` jobs (see lsst-dm/jenkins-dm-jobs#955) to add Jenkins-specific metadata to the upload.
=> DM-39412: Add Jenkins build ID to ap_verify Sasquatch metadata

.pre-commit-config.yaml, pipelines/matchedVisitQualityCore.yaml, python/lsst/analysis/tools/actions/vector/selectors.py, python/lsst/analysis/tools/atools/astrometricRepeatability.py, python/lsst/analysis/tools/atools/diffMatched.py, python/lsst/analysis/tools/atools/photometricRepeatability.py
This PR implements metrics modelPhotRepStar1-4 and psfPhotRepStar1-4 in analysis_tools. All that was required was (1) modifying stellarPhotometricRepeatability.py to use a "RangeSelector" (i.e., select values between an upper and lower threshold) instead of "ThresholdSelector", and (2) implementing the metrics in the matchedVisitQualityCore.yaml pipeline.
Note that only the stellar repeatability metrics were added. Galaxy metrics will require a different implementation since `isolated_star_sources` uses only stars.
=> DM-38974: Move photometric repeatability metrics from faro to analysis_tools

python/lsst/analysis/tools/actions/plot/histPlot.py, python/lsst/analysis/tools/actions/scalar/scalarActions.py, python/lsst/analysis/tools/atools/photometricRepeatability.py
This ticket makes the PF1 metric calculation ("stellarPhotRepeatOutlierFraction") use a threshold _relative to the median_ as defined in the SRD, rather than taking a simple threshold in rms. It involved changing the ScalarAction and HistPlot.
=> DM-39332: Fix the PF1 metric to be threshold relative to mean

python/lsst/analysis/tools/atools/photometricRepeatability.py
This PR implements a fix to ensure that "PF1" (the fraction of outliers in photometric repeatability) is calculated correctly in analysis_tools. The previous implementation did not actually set the value given in config, so the configured values needed to be moved to a `finalize` method to ensure that they are properly assigned.
=> DM-40768: Stellar photometric repeatability in analysis_tools is not applying defaults correctly

python/lsst/analysis/tools/actions/plot/propertyMapPlot.py, python/lsst/analysis/tools/tasks/propertyMapTractAnalysis.py, tests/test_propertyMapPlot.py
While I was at it, I fixed typos, tweaked the plot action to work with the test, and made other necessary adjustments throughout.
=> DM-41182: Add basic functionality test for PropertyMapTractAnalysisTask

.gitignore, python/lsst/analysis/tools/interfaces/datastore/_sasquatchDatastore.py, tests/test_sasquatchDatastore.py
Also adds a trivial unit test for SasquatchDatastore to verify that it can be instantiated and simple `Butler.put` works on it.
=> DM-41598: Add missing abstract methods to SasquatchDatastore

python/lsst/analysis/tools/contexts/_baseContext.py, python/lsst/analysis/tools/interfaces/_actions.py, python/lsst/analysis/tools/interfaces/_analysisTools.py, python/lsst/analysis/tools/interfaces/_interfaces.py, python/lsst/analysis/tools/interfaces/_stages.py, setup.cfg
This commit adds an interface that can be used to represent multi-dimensional data like images, or stacks of images. It uses an industry standard interface to ensure analysis tools can work with a wide variety of data types from numpy arrays to pytorch models.
=> DM-42685 Add a Tensor interface to analysis tools

python/lsst/analysis/tools/interfaces/_stages.py
The ticket adding the Tensor interface make a change to BasePrep to make it more logically sound to the types that are possible in keyed data. This unfortunately overlooked usage that existed that relied on ill defined behavior. This is a fixup to that, restoring existing behavior is a slightly more gaurded way.
=> DM-42685-hotfix: Fix breakage in BasePrep

python/lsst/analysis/tools/interfaces/_stages.py
Add input schema was adding the same vectors multiple times due to how serialization was happening with pickle. Make this idempotent across the number of times this method is called. This is also a good change to make to guard against mistakes by the user specifying a vector multiple times.
=> DM-42685-hotfix2 Make BasePrep.addInputSchema idempotent

python/lsst/analysis/tools/interfaces/_analysisTools.py, tests/test_analysisTool.py
Add a class method to AnalysisTool which allows a tool defined in a pipeline to be loaded into a python session.
=> DM-42820: Add method to load an AnalysisTool from a pipeline

pipelines/coaddQualityCore.yaml, python/lsst/analysis/tools/tasks/astrometricCatalogMatch.py
for PhotometricCatalogMatchTask and AstrometricCatalogMatchTask. Pipeline levels overrides cannot be overriden by obs packages, and PhotometricCatalogMatchTask was being overriden by the default anyway
=> DM-42971: Remove pipeline-level overrides

pipelines/exposureCore.yaml, python/lsst/analysis/tools/atools/calibration.py, python/lsst/analysis/tools/tasks/calibrationAnalysis.py
I've included `quantityKey` and `unit` as input parameters to `calibration.py`. The reason for the former is to simplify the pipeline.yaml file, while the latter allows for the unit to be included in the dynamically-poduced zAxisLabel.
Please see the [JIRA ticket](https://jira.lsstcorp.org/browse/DM-42672) for plot examples.
Jenkins currently running.
=> Tickets/DM-42672: Create FocalPlaneGeometryPlots for biasMean, biasNoise, biasCRNoise, biasShiftCount

python/lsst/analysis/tools/tasks/photometricCatalogMatch.py
This hack is needed to make this task work with ops rehearsal 3.
=> DM-43049: Add more plots to LsstComCamSim

python/lsst/analysis/tools/actions/keyedData/calcDistances.py, python/lsst/analysis/tools/tasks/associatedSourcesTractAnalysis.py
This refactors the loops in calcDistances to be vectorized and get a 10x speed increase.  In addition, it adds downsampling which gets another 5-10x speed increase in the densest fields.
One algorithmic change from the old version is that now the computation of `sepResiduals` changes from from `separations - median(separations)` to `separations - mean(separations)` because this is much easier to vectorize.
There is also a small fix for empty tracts.
=> DM-43238: Refactor calcDistances.py for a 50-100x speed increase in AnalyzeMatchedVisitCore

pipelines/apDetectorVisitQualityCore.yaml, python/lsst/analysis/tools/tasks/trailedDiaSrcDetectorVisitAnalysis.py
=> DM-41108: Temporarily remove broken AP metrics

python/lsst/analysis/tools/atools/__init__.py, python/lsst/analysis/tools/atools/calexpMetrics.py, python/lsst/analysis/tools/interfaces/_analysisTools.py, python/lsst/analysis/tools/tasks/__init__.py, python/lsst/analysis/tools/tasks/calexpSummaryAnalysis.py
This ticket involves changes to two repositories: this repository (analysis_tools) and pipe_tasks. Here, I'm adding a new analysis tool task and atool to extract summary statistics from a calexp's metadata and write them to sasquatch.
=> DM-43231: Create Analysis Tool to send visitSummary info to sasquatch

pipelines/calexpMetrics.yaml
Enables the production and writing of metrics generated from an existing calexp's summary statistics.
=> DM-43477: Create pipeline yaml file to create calexp summary metrics from existing calexps' summary stats

python/lsst/analysis/tools/tasks/reconstructor.py
Removed collections keyword from butler.get(ref,...) in tasks/reconstructor.py
=> DM-44002: Fix DatasetRef warning when using the analysis_tools reconstructor

pipelines/apDetectorVisitQualityCore.yaml, python/lsst/analysis/tools/tasks/trailedDiaSrcDetectorVisitAnalysis.py
With the trailed source filtering moved to `filterdiaSourceCatalog`, its type has changed from pandas dataframe to ArrowAstropy. This required an update to `analysis_tools.`
=> DM-41063: Move trailed source filtering to filterDiaSourceCatalog

pipelines/matchedVisitQualityCore.yaml, python/lsst/analysis/tools/actions/plot/histPlot.py, python/lsst/analysis/tools/atools/photometricRepeatability.py
This ticket creates new metrics and plots that calculate photometric repeatability using `calibFlux` instead of `psfFlux`. The comparison between these is informative to the Photometric Calibration Science Unit in assessing different contributions to the error budget.
Implementing the focal plane plot required updating the `StellarPhotometricResidualsFocalPlane` class so that it will correctly apply config overrides.
Finally, I added formatting to the `histPlot` routine to make the reference_label formatting not have too many digits after the decimal.
=> DM-44302: Implement photometric repeatability metrics and plots in analysis_tools with calib_fluxes

pipelines/wholeSkyCore.yaml, python/lsst/analysis/tools/tasks/__init__.py, python/lsst/analysis/tools/tasks/makeMetricTable.py, python/lsst/analysis/tools/tasks/metricAnalysis.py
Tables that include data for the metrics across all of the tracts in the sky are useful for a variety of reasons, including plotting whole sky plots.
=> DM-42595: Make a whole sky table of metrics

python/lsst/analysis/tools/interfaces/_task.py
The base connection's class doesn't actually override any attribute-setting hooks, but if it did, we'd want it to fire.
We also don't need to explicitly update the self.<connection-type> sets anymore, as those are handled by the metaclass.
=> DM-44583: Use setattr instead of object.__setattr__.

python/lsst/analysis/tools/tasks/gatherResourceUsage.py
queryDatasetTypes no longer supports regexes.
=> DM-36457: Use globs instead of regexes for dataset type patterns

pipelines/apDetectorVisitFakesCore.yaml, python/lsst/analysis/tools/atools/__init__.py, python/lsst/analysis/tools/atools/diaFakeMetrics.py, python/lsst/analysis/tools/tasks/__init__.py, python/lsst/analysis/tools/tasks/diaFakesDetectorVisitAnalysis.py, python/lsst/analysis/tools/tasks/diaFakesVisitAnalysis.py
Adding metrics that calculate fraction of fakes found.
Next iteration is to provide a completeness per bandpass in magnitude space.
=> DM-39900: Develop improved metrics for completeness based on injected sources

pipelines/cpCore.yaml, python/lsst/analysis/tools/actions/plot/elements/scatterElement.py
=> DM-44545: Design initial calibration report format

pipelines/matchedVisitQualityCore.yaml
After the calibration refactoer PreSources and Sources are based on two separate rounds of detection.
isolatedStarAssociation is run on both separately and yields two sets of match catalogs.
analyzeMatchedVisitCore is based on: isolated_star_sources
analyzeMatchedPreVisitCore is based on:  isolated_star_presources
=> DM-46642: Run matchVisitQuality tasks on outputs of isolatedStarSourceAssociation.

python/lsst/analysis/tools/tasks/refCatSourcePhotometricAnalysis.py
All other refCat*Analysis tasks have these, so this one should do.
=> DM-46188: Add connection templates to refCatSourcePhotometricAnalysis.

python/lsst/analysis/tools/atools/calexpMetrics.py
Where possible, units now align with those in afw/image/_exposureSummaryStats.py
=> DM-47111: Fix units in analysis_tools/.../calexpMetrics.py

pipelines/matchedVisitQualityCore.yaml, python/lsst/analysis/tools/atools/astrometricRepeatability.py, python/lsst/analysis/tools/tasks/associatedSourcesTractAnalysis.py, python/lsst/analysis/tools/tasks/sourceObjectTableAnalysis.py
Use isolated_star_presources for matches and sourceTable_visit for measurements.
=> DM-47010: Change default to assume preSources used for matching

python/lsst/analysis/tools/actions/plot/propertyMapPlot.py
This also fixes deprecated usage in skyproj.
=> DM-44743: Fix crash when trying to zoom on an empty map

pipelines/visitQualityCore.yaml, python/lsst/analysis/tools/tasks/sourceTableVisitAnalysis.py
This avoids mistakenly leaving the default input unchanged when reusing for `preSources` (instead of `sources`).
=> DM-48019: Add explicit input for sourceTable_visit in analyzeSourceTableCore

python/lsst/analysis/tools/tasks/sourceObjectTableAnalysis.py
This exact logic was needed in another method called applyAstrometricCorrections on a different task; I'm a little concerned there might be some code duplication there, but I don't have time to dig too deeply there.
=> DM-48655: Add pandas index to visit table on read if needed.

python/lsst/analysis/tools/actions/plot/histPlot.py, python/lsst/analysis/tools/atools/astrometricRepeatability.py
When I was looking at plots output for Astrometry, label were out of the figure. This is fixing that and I fixed limit of plot to make easier to compare between different run.
=> DM-47181: Modify hist plot output format for Astrometry.

python/lsst/analysis/tools/tasks/sourceObjectTableAnalysis.py
This converts the quantity passed to `query_radius` method to a numpy array instead of a Pandas series.
=> DM-49196: Convert to numpy array before passing to the matcher

python/lsst/analysis/tools/bin/verifyToSasquatch.py, tests/test_verifyToSasquatch.py
This PR is moving `_AppendDict` class in `verifyToSasquatch.py` to be in `lsst.utils` package, so it can be widely used.
=> DM-46249-hotfix3 : Upload analysis_tools metrics from ap_verify so they can be retrieved in Chronograf

pipelines/apDetectorVisitQualityCore.yaml
Only for metadata from tasks that might raise NoWorkFound during processing, and might not set all expected metadata.
=> DM-49282: Raise NoWorkFound in AP metrics if any metadata entries are missing.

python/lsst/analysis/tools/tasks/associatedSourcesTractAnalysis.py
Astropy table vstack and join provide no control over merging of metadata from each input table. For provenance we do not want to naively merge provenance keywords (and want to write new provenance later) so for now it is best to strip butler provenance information before merging.
=> DM-49505: Strip provenance from table metadata before stacking

python/lsst/analysis/tools/tasks/associatedSourcesTractAnalysis.py
Astropy table vstack and join provide no control over merging of metadata from each input table. For provenance we do not want to naively merge provenance keywords (and want to write new provenance later) so for now it is best to strip butler provenance information before merging.
=> DM-49505 (v29): Strip provenance from table metadata before stacking

python/lsst/analysis/tools/interfaces/datastore/_dispatcher.py
The JSON encoder inside the requests library will throw an exception on np.float32 values (but not np.float64), so these need to be explicitly cast upstream.
=> DM-49765: Cast np.float32 to float when dispatching metrics.

pipelines/visitQualityCore.yaml
This isn't an analysis task and its replacement will be run along with coadd-level tasks in existing pipelines.
=> DM-49727: Remove objectEpochTable from visitQualityCore

python/lsst/analysis/tools/interfaces/_metricMeasurementBundle.py, python/lsst/analysis/tools/interfaces/datastore/_dispatcher.py
Without this, single-precision metrics result in "TypeError: Object of type float32 is not JSON serializable"
=> DM-49074: Explicitly cast float32 to avoid JSON error. Backport v29.

pipelines/visitQualityCore.yaml
This isn't an analysis task and its replacement will be run along with coadd-level tasks in existing pipelines.
=> DM-49727-v29: Remove objectEpochTable from visitAnalysis

python/lsst/analysis/tools/actions/keyedData/calcDistances.py, python/lsst/analysis/tools/actions/plot/histPlot.py
This greatly limits the memory usage and runs in a reasonable amount of time (5-10 seconds for the matching on USDF).
=> DM-50369: Use brute-force matching for large radii in astrometric association.

python/lsst/analysis/tools/interfaces/datastore/_dispatcher.py
This PR broadens the request error handling in `_dispatcher.py` to include cluster and topic setup (which are more likely than the upload to encounter network problems because they run first) and to include failure modes that don't return an HTTP response.
=> DM-52115: Handle exceptions from all SasquatchDispatcher's network operations

python/lsst/analysis/tools/actions/plot/histPlot.py, python/lsst/analysis/tools/actions/plot/scatterplotWithTwoHists.py
This is branched-off another bug-fix ticket branch (DM-52046) so by reviewing this PR you'll review them both at the same time. Both are small edits, so it should be straightforward. There's one commit each:
DM-52046: Add catch for no valid range in histPlot
DM-52576: Reconcile low stats threshold in scatterPlotWithTwoHists
=> DM-52576: LSSTCam DRP error in photometricRefCatObjectTract: "cannot access local variable 'meds' where it is not associated with a value"

python/lsst/analysis/tools/interfaces/_stages.py, python/lsst/analysis/tools/interfaces/_task.py, python/lsst/analysis/tools/tasks/metadataExposureDetectorAnalysis.py
For missing metadata keys, raise an `AlgorithmError` subclass, catch it in analysis_tools actions, then either re-raise as `AnnotatedPartialOutputsError` or proceed when `--no-raise-on-partial-outputs` is enabled.
_Update:_ We now catch all exceptions, wrap them in a dedicated `AlgorithmError`, and re-raise as `AnnotatedPartialOutputsError`.
=> DM-50671: Investigate `analyzeAmpOffsetMetadata` failure on detectors 120–122 due to missing ISR metadata in w18
