lsst/analysis_tools

- python/lsst/analysis/tools/tasks/reconstructor.py
The reconstructAnalysisTools function should handle when inputs
are expected to be multiple.
> Dm-35650: Handle multiple inputs in reconstruction

- python/lsst/analysis/tools/analysisMetrics/limitingMagnitudeMetric.py
- python/lsst/analysis/tools/analysisPlots/magDiff.py
Figured this was an easy one to get my feet wet on...
Seems like these just slipped through the cracks on DM-35683 (#12).
> DM-37050: Rename StarSelector columnKey to vectorKey

- python/lsst/analysis/tools/actions/plot/barPlots.py
Added a bar plot to analysis.tools.plots that can take any number of vector inputs and plot them as one or more bar graphs.
> DM-36673: Add barPlots to analysis_tools

- bin.src/SConscript
- examples/SConscript
> DM-35962: Remove examples/ from all packages

- python/lsst/analysis/tools/tasks/reconstructor.py
> DM-38210: Use butler.get() rather than deprecated getDirect()

- python/lsst/analysis/tools/interfaces/_task.py
Use a config class's applyConfigOverrides to parse Pipelines for override values which will be applied to  MetricMeasurementBundles from a Pipeline's supplied parameters.
> DM-39130: Allow Sasquatch bundle info setting from Pipelines

- pipelines/coaddQualityCore.yaml
- python/lsst/analysis/tools/actions/plot/rhoStatisticsPlot.py
- python/lsst/analysis/tools/actions/plot/xyPlot.py
- python/lsst/analysis/tools/atools/shapes.py
The PR applies the selection to all the relevant fields before computing rho statistics.
Note to self:
> DM-38770: Resolve the discrepancies in rho statistics plots compared to analysis_drp

- doc/lsst.analysis.tools/getting-started.rst
Edit a sentence to test making a pull request
> DM-39423: modify a sentence of getting started guide

- pipelines/coaddDiffMatchedQualityExtended.yaml
- python/lsst/analysis/tools/actions/vector/calcBinnedStats.py
- python/lsst/analysis/tools/atools/diffMatched.py
- tests/test_actions.py
- tests/test_metrics.py
... `if self.parameterizedBand`, which is always True for the only tool using this action at the moment.
> DM-39345: Prefix CalcBinnedStats metric names by band

- python/lsst/analysis/tools/actions/plot/skyPlot.py
- python/lsst/analysis/tools/tasks/associatedSourcesTractAnalysis.py
- python/lsst/analysis/tools/tasks/objectTableSurveyAnalysis.py
> DM-39367: Remove hardcoded skymap names

- python/lsst/analysis/tools/interfaces/datastore/_sasquatchDatastore.py
Depends on lsst/daf_butler#892
> DM-41043: Use new GenericBaseDatastore location

- python/lsst/analysis/tools/atools/photometry.py
Avro seems to have an issue with - in metric names, this ticket removes its use.
> DM-42062 Change metric name

- python/lsst/analysis/tools/interfaces/datastore/_sasquatchDatastore.py
There was a slight change to the Datastore interface upstream in daf_butler -- added new methods to conform with it.
> DM-42317: Update SasquatchDatastore for Datastore changes

- pipelines/exposureCore.yaml
- python/lsst/analysis/tools/actions/plot/focalPlanePlot.py
- python/lsst/analysis/tools/atools/__init__.py
- python/lsst/analysis/tools/atools/calibration.py
- python/lsst/analysis/tools/tasks/__init__.py
- python/lsst/analysis/tools/tasks/calibrationAnalysis.py
The changes shown here are actually from three related tickets (DM-42671, DM-42651, DM-42648), so there are three different branches. The branches are, however, linear, so they are effectively a set of three commits. This branch (DM-42648) is the last of the branches, so by merging this branch, the changes made in all branches will be merged into main.
> Tickets/DM-42648: Create FocalPlaneGeometryPlot for Readnoise median

- python/lsst/analysis/tools/actions/plot/plotUtils.py
- python/lsst/analysis/tools/actions/plot/scatterplotWithTwoHists.py
- python/lsst/analysis/tools/actions/vector/selectors.py
- python/lsst/analysis/tools/atools/diffMatched.py
This came up with some MultiProFit plots on ci_imsim. Add it to the list of easy fixes that ought not to be necessary if all of the relevant flags/selection were applied to the input data, I suppose.
> DM-42157: Skip scatterplot bin plot for non-finite sigMadY

- pipelines/apDetectorVisitQualityCore.yaml
Needs future fix from DM-43401
> DM-43402: Turn off good/bad diaSource ratio metric

- python/lsst/analysis/tools/actions/plot/elements/__init__.py
- python/lsst/analysis/tools/actions/plot/elements/plotInfoElement.py
- python/lsst/analysis/tools/actions/plot/gridPlot.py
- python/lsst/analysis/tools/actions/plot/plotUtils.py
Added a PlotInfoElement for use in element-wise analysis tools plot creation. Also made changes to GridPlot to accommodate the new PlotInfoElement.
> DM-43898: Create PlotInfo analysis tools plot element

- pipelines/diaObjectAssociatedSources.yaml
- tests/test_contexts.py
This PR fixes a reference to a task that was renamed on #147.
> DM-44411: Fix bit-rot in AP pipelines

- python/lsst/analysis/tools/interfaces/datastore/_sasquatchDatastore.py
Not implemented in sasquatch
Requires lsst/daf_butler#1105
> DM-46776: Add new ingest_zip method required to Datastore

- pipelines/apDetectorVisitQualityCore.yaml
- python/lsst/analysis/tools/atools/diaFakeMetrics.py
- python/lsst/analysis/tools/tasks/diffimTaskDetectorVisitMetricsAnalysis.py
Update the diaFakeMetrics to accomodate for new matching scheme for dia fakes.
> DM-46105: Add matching for diaSrcs and split metrics between pre & post filtering diaSrcs

- python/lsst/analysis/tools/actions/scalar/scalarActions.py
- python/lsst/analysis/tools/math.py
- tests/test_actions.py
Not all these changes are strictly necessary to address the ticket, but I thought it better have consistency across actions where possible.
> DM-42906: Edit scalarActions to accommodate Tensors

- pipelines/wholeSkyCore.yaml
- python/lsst/analysis/tools/tasks/makeMetricTable.py
Generalise makeMetrticTable.py to work with any type of metric bundle, not just tract level.
> DM-44485: Make tables of metrics for visit level data

- python/lsst/analysis/tools/interfaces/datastore/_sasquatchDatastore.py
> DM-35396: Add the provenance parameter to Datastore put

- README.rst
> Fix broken link to pipelines documentation

- pipelines/coaddQualityCore.yaml
- pipelines/wholeSkyCore.yaml
Note that there is an additional PR on drp_pipe for this ticket.
> DM-49145: Change string in stellar locus names from "PSFP" to "PSF"

- python/lsst/analysis/tools/atools/photometricRepeatability.py
Title says "Investigate", but this merge is the fix that addresses what was found. It ensures that the signal-to-noise cut takes place prior to group formation.
> DM-49077: Investigate strange PA1 metric on DP1 processing tract 5063, r band

- pipelines/coaddDiffMatchedInjectedCore.yaml
This reverts commit e21ac35e55cbeda0717190aa98ea1f739f14f75d, reversing changes made to f681471983f4721aa62e0460c26ba2d61856c8f4.
> Revert "Merge pull request #361 from lsst/tickets/DM-47210"

- python/lsst/analysis/tools/interfaces/_metricMeasurementBundle.py
Explicitly cast float32 to avoid JSON error. Without this, single-precision metrics result in "TypeError: Object of type float32 is not JSON serializable"
> DM-49074: Cast table columns to single precision in SDM-standardization functors

- python/lsst/analysis/tools/interfaces/datastore/_dispatcher.py
- python/lsst/analysis/tools/utils.py
- requirements.txt
- tests/test_utils.py
Harden sasquatch http client requests with retry adapter.
> DM-49354 : Implement http request retry logic in sasquatch dispatcher

- pipelines/cpCore.yaml
Update column name.  Fix units for bias and dark plots.
> DM-49219: Fix cp_verify noise tests

- pipelines/apDetectorVisitQualityCore.yaml
- python/lsst/analysis/tools/tasks/diaFakesDetectorVisitAnalysis.py
- python/lsst/analysis/tools/tasks/diaFakesVisitAnalysis.py
A few small cleanups on separate commits: one was helpful for organization and the other fixes a bug that prevented building a graph visualization.
> DM-49875: AP renaming for RFC-1088
